#!/usr/local/bin/python3
"""
A subscript of mc3 to select a sample of a catalog based on specified criteria.
"""

from AstroLib import *

################################################################################

##  Parser.

Parser  = Io.ArgParser( sys.argv )

Parser.add_argument(
    name            = "configs_file",
    default         = None,
    type            = str,
    key             = None,
    flag            = "-c",
    contains        = None,
    required        = True,
    description     = "The configs file for field plot."
)

Parser.add_argument(
    name            = "out_file",
    default         = None,
    type            = str,
    key             = None,
    flag            = "-o",
    contains        = None,
    required        = True,
    description     = "The output file for the field plot to save to."
)

Parser.parse_arguments()
Parser.check_satisfied()

################################################################################

configs     = Io.read( Parser.get("configs_file") )

FieldPlot   = PlotLib.FieldPlot()
FieldPlot.setup()

for config in configs:

    print( "Adding %s to the plot." % config["catalog"] )

    dat     = Io.read( config["catalog"] )
    good    = np.where( dat["alpha"] > 0 )[0]
    alpha   = dat["alpha"][good]
    delta   = dat["delta"][good]

    FieldPlot.plot(
        alpha, delta,
        marker=config["marker"], ms=config["ms"]
    )

FieldPlot.save( Parser.get("out_file") )
