#!/usr/local/bin/python3
"""
Script to run PySEx functions.
"""

from AstroLib import *

################################################################################

##  Create the main argument parser.

Parser  = Io.ArgParser( sys.argv )

Parser.add_argument(
    name            = "default_cfg",
    default         = False,
    type            = str,
    key             = None,
    flag            = "-c",
    contains        = None,
    required        = False,
    description     = "SExtractor configs (.sex) file."
)

Parser.add_argument(
    name            = "batch_cfg",
    default         = False,
    type            = str,
    key             = None,
    flag            = "-b",
    contains        = None,
    required        = False,
    description     = "Configs file used for batch image mode."
)

Parser.parse_arguments()
Parser.check_satisfied()

################################################################################

##  For now, let's just ignore the option just to run SExtractor.
##  It's only interesting in batch mode, now.

if Parser.get("default_cfg") and Parser.get("batch_cfg"):

    default_cfg     = Parser.get("default_cfg")
    batch_cfg       = Parser.get("batch_cfg")

    Fits.SEx.batch_sex( default_cfg, batch_cfg, detection=None, command="sex" )

else:

    raise Exception( "Please provide default (-c) and batch (-b) configs files.")
