#!/usr/local/bin/python3
"""
Run/cln.py

This script cleans all unwanted files from the current working directory.
"""

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals

import os, sys
import shutil as sh

################################################################################

## Specify unwanted items.

unwanted_beginnings = [

]

unwanted_endings    = [
    "~","#",".pyc",
]

unwanted_dirs     = [
    "__pycache__",
]

## Get path from sys.argv.

if len( sys.argv ) == 1:

    path    = './'

elif len( sys.argv ) == 2:

    path    = sys.argv[1] + '/'

else:

    print("There are too many arguments.")

## Iterate through the directory and remove all unwanted items.

for f in os.listdir( path ):

    for beginning in unwanted_beginnings:

        if f[:len(beginning)] == beginning:

            os.remove( path + f )
            print( "Removed " + f + ".")

    for ending in unwanted_endings:

        if f[-len(ending):] == ending:

            os.remove( f )
            print( "Removed " + f + ".")

    for total in unwanted_dirs:

        if f  == total:

            sh.rmtree( path + f )
            print( "Removed " + f + ".")
