#!/usr/local/bin/python3
"""
Run/cln.py

This script cleans all unwanted files from the current working directory.
"""

from AstroLib import *

################################################################################

##  Argument Parser

Parser  = Io.ArgParser( 

